#
# Config for Coveralls
#
---
service_name: travis-pro
repo_token: QgmM2dny7xjUpRzyHxO93nZ9K4S7loCcz

# Local Variables:
# mode: YAML
# yaml-indent-offset: 2
# indent-tabs-mode: nil
# End:
# vim:sw=2:ts=2:expandtab:textwidth=79:autoindent
